import type { Badge } from "./Badges.type";

export interface FitbitProfile {
    age:                      number;
    ambassador:               boolean;
    autoStrideEnabled:        boolean;
    avatar:                   string;
    avatar150:                string;
    avatar640:                string;
    averageDailySteps:        number;
    challengesBeta:           boolean;
    clockTimeDisplayFormat:   string;
    corporate:                boolean;
    corporateAdmin:           boolean;
    dateOfBirth:              string;
    displayName:              string;
    displayNameSetting:       string;
    distanceUnit:             string;
    encodedId:                string;
    features:                 {  exerciseGoal: boolean; };
    firstName:                string;
    foodsLocale:              string;
    fullName:                 string;
    gender:                   string;
    glucoseUnit:              string;
    height:                   number;
    heightUnit:               string;
    isBugReportEnabled:       boolean;
    isChild:                  boolean;
    isCoach:                  boolean;
    languageLocale:           string;
    lastName:                 string;
    legalTermsAcceptRequired: boolean;
    locale:                   string;
    memberSince:              string;
    mfaEnabled:               boolean;
    offsetFromUTCMillis:      number;
    sdkDeveloper:             boolean;
    sleepTracking:            string;
    startDayOfWeek:           string;
    strideLengthRunning:      number;
    strideLengthRunningType:  string;
    strideLengthWalking:      number;
    strideLengthWalkingType:  string;
    swimUnit:                 string;
    temperatureUnit:          string;
    timezone:                 string;
    topBadges:                Badge[];
    waterUnit:                string;
    waterUnitName:            string;
    weight:                   number;
    weightUnit:               string;
}
